#pragma once

// Declare in header to avoid conflicts with
// function prototypes auto-generated by Arduino

struct color {
    int r;
    int g;
    int b;
};

struct Reading {
    String timestamp;
    float temperature;
    float humidity;
    float air_pressure;
    int brightness;
    color light_color;
};
